version: '3.8'
services:
  app:
    build: .
    container_name: my-nestjs-app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: user # Thay bằng user trong DATABASE_URL của bạn
      POSTGRES_PASSWORD: password # Thay bằng password
      POSTGRES_DB: mydb # Thay bằng tên db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: