name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm' # Sử dụng cache của npm

    - name: Install dependencies
      # Sử dụng npm ci để cài đặt nhanh và nhất quán trong môi trường CI
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test